### ISSUE TITLE
glucometer.py always crashes with python error

### ISSUE THREAD

**Issue by stanljp1** [glucometers-tech/glucometerutils#100]
Running glucometer.py always results in the following error:

```
> Traceback (most recent call last):
>   File "glucometer.py", line 7, in <module>
>     from glucometerutils import glucometer
>   File "/home/john/glucometerutils-main/glucometerutils/glucometer.py", line 12, in <module>
>     from glucometerutils import common, driver, exceptions
>   File "/home/john/glucometerutils-main/glucometerutils/common.py", line 57, in <module>
>     @attr.s(auto_attribs=True)
> AttributeError: module 'attr' has no attribute 's'
```
Not clear if this is a python versioning issue, undocumented dependency, or operator error.

**Comment by stanljp1** [comment]
Was improperly installed
