### ISSUE TITLE
One Touch verio reflect

### ISSUE THREAD

**Issue by SmashinDave** [glucometers-tech/glucometerutils#130]
Hello,
I've got no coding skills but was able to install everything hoping to download the readings stored in my Onetouch Verio Reflect to import the data in a (non proprietary) app.
My issue is when I connect the meter to my computer (running Linux Mint), it is nowhere to be found (isn't listed by lsusb).
I assumed maybe hastily that the driver would be the same for the verio reflect as for the other versions but it might not be the case ; do you know about this?
So when I try a command, this is what happens: 
```
glucometer --driver otverio2015 info
Traceback (most recent call last):
  File "/home/dave/glucometerutils/glucometerutils-venv/bin/glucometer", line 8, in <module>
    sys.exit(main())
  File "/home/dave/glucometerutils/glucometerutils-venv/lib/python3.10/site-packages/glucometerutils/glucometer.py", line 118, in main
    device = requested_driver.device(args.device)
  File "/home/dave/glucometerutils/glucometerutils-venv/lib/python3.10/site-packages/glucometerutils/drivers/otverio2015.py", line 117, in __init__
    raise exceptions.CommandLineError(
glucometerutils.exceptions.CommandLineError: --device parameter is required, should point to the disk device representing the meter.
```

Any idea of what I could do to make the computer detect the device? 

Thanks a million for the work you've put in this solution, I was about to give up but I'm seeing a glimmer of hope now; I can't bring myself to use the proprietary solution.
Best wishes
Dave

**Comment by Flameeyes** [comment]
Hi Dave,

If `lsusb` is not detecting the device, there's not going to be much to connect to unfortunately. But the Reflect _is_ supposed to have a data port. So if this is happening consistently, it might be that the cable is a charge-only cable that misses the data wires (lots of cables that come with devices from Amazon and AliExpress suffer from that problem), so I would suggest you try with a different cable.

On the other hand, OneTouch has been fairly annoying with changing protocols more often than it's reasonable for them, so it might be that it won't be working with the older Verio driver and it'd have to be reverse engineered.

I don't have one of those devices at hand right now, and while it looks like I might be able to grab one off Amazon, I'm not sure if I have time before the new year to reverse it 😔

**Comment by SmashinDave** [comment]
Hi Flameeyes
You were spot-on, it was the cable!
So now the computer sees the device but there is an err13 when I try to run dump or info.
Any idea?
Thanks again

**Comment by SmashinDave** [comment]
Hello,
This is just to let you know that I finally managed to download the readings from my glucometer using your script.
So the otverio2015 driver works fine with the Onetouch verio Reflect provided the dependencies are installed correctly (my bad).
Many thanks again for making this utility available.
