### ISSUE TITLE
construct 2.9 API changes

### ISSUE THREAD

**Issue by ednlina** [glucometers-tech/glucometerutils#38]
Trying for the first time to use this code...  output in beginning is my debugging...
(glucometers-venv) eds-mac-pro:~ edm$ glucometer --driver ${DRIVER} dump
using driver: otverioiq
prior to lifescan_binary_protocol
command_prefix: 3
<module 'construct' from '/Users/edm/glucometers-venv/lib/python3.5/site-packages/construct/__init__.py'>
Traceback (most recent call last):
  File "/Users/edm/glucometers-venv/bin/glucometer", line 9, in <module>
    load_entry_point('glucometerutils==1', 'console_scripts', 'glucometer')()
  File "/Users/edm/glucometers-venv/lib/python3.5/site-packages/glucometerutils/glucometer.py", line 74, in main
    driver = importlib.import_module('glucometerutils.drivers.' + args.driver)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/Users/edm/glucometers-venv/lib/python3.5/site-packages/glucometerutils/drivers/otverioiq.py", line 35, in <module>
    0x03, False)
  File "/Users/edm/glucometers-venv/lib/python3.5/site-packages/glucometerutils/support/lifescan_binary_protocol.py", line 38, in LifeScanPacket
    command_prefix_construct = construct.Const(construct.Byte, command_prefix)
  File "/Users/edm/glucometers-venv/lib/python3.5/site-packages/construct/core.py", line 2440, in __init__
    super(Const, self).__init__(subcon)
  File "/Users/edm/glucometers-venv/lib/python3.5/site-packages/construct/core.py", line 549, in __init__
    raise TypeError("subcon should be a Construct field")
TypeError: subcon should be a Construct field
(glucometers-venv) eds-mac-pro:~ edm$ 

I see in other forums that construct apparently changed an api?

**Comment by Flameeyes** [comment]
Sigh, looks like construct 2.9 broke API again? :/

**Comment by arekbulski** [comment]
I am the Construct developer, will address this issue shortly.

**Comment by arekbulski** [comment]
See #39 .

**Comment by arekbulski** [comment]
At first glance, you seem to hit a change that was introduced just before 2.9 which was: Const changed order so now its Const(value, type). See [transition page ](https://construct.readthedocs.io/en/latest/transition29.html)for 2.9 changes.

**Comment by arekbulski** [comment]
#40  fixes this and potential issues with construct.

**Comment by eploft** [comment]
Hi!
I've wrote the Issue #41.
I've tried with construct==2.8.22 the error report is nearly the same (different line number).
I've also tried the "setup.py build" and "setup.py install". Also didn't help.
Any other ideas?

~/glucometerutils $ python3.5 glucometer.py --driver fslibre --device hidraw3 dump
Traceback (most recent call last):
  File "glucometer.py", line 7, in <module>
    glucometer.main()
  File "/home/xyz/glucometerutils/glucometerutils/glucometer.py", line 73, in main
    driver = importlib.import_module('glucometerutils.drivers.' + args.driver)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/xyz/glucometerutils/glucometerutils/drivers/fslibre.py", line 26, in <module>
    from glucometerutils.support import freestyle
  File "/home/xyz/glucometerutils/glucometerutils/support/freestyle.py", line 29, in <module>
    'hid_report' / construct.Const(construct.Byte, 0),
  File "/usr/local/lib/python3.5/dist-packages/construct/core.py", line 1277, in __init__
    super(Const, self).__init__(subcon)
  File "/usr/local/lib/python3.5/dist-packages/construct/core.py", line 287, in __init__
    raise TypeError("subcon should be a Construct field")
TypeError: subcon should be a Construct field

The installed construct-version:

~/glucometerutils $ cat /usr/local/lib/python3.5/dist-packages/construct/version.py 
version = (2,8,22)
version_string = "2.8.22"
release_date = "2018.01.18"

oder 

 ~/glucometerutils $ python3.5 -m pip list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
apt-clone (0.2.1)
apt-xapian-index (0.47)
apturl (0.5.2)
blinker (1.3)
Brlapi (0.6.4)
chardet (2.3.0)
command-not-found (0.3)
**construct (2.8.22)**
cryptography (1.2.3)
defer (1.0.6)
dirspec (13.10)
glucometerutils (1)
httplib2 (0.9.1)
idna (2.0)
louis (2.6.4)
lxml (3.5.0)
Mako (1.0.3)
MarkupSafe (0.23)
oauthlib (1.0.3)
onboard (1.2.0)
oneconf (0.3.9)
pexpect (4.0.1)
Pillow (3.1.2)
pip (9.0.1)
piston-mini-client (0.7.5)
psutil (3.4.2)
ptyprocess (0.5)
pyasn1 (0.1.9)
pycrypto (2.6.1)
pycups (1.9.73)
pycurl (7.43.0)
pygobject (3.20.0)
PyICU (1.9.2)
PyJWT (1.3.0)
python-apt (1.1.0b1+ubuntu0.16.4.1)
python-debian (0.1.27)
python-xapp (1.0.0)
pyxdg (0.25)
reportlab (3.3.0)
requests (2.9.1)
sessioninstaller (0.0.0)
setproctitle (1.1.8)
setuptools (38.5.1)
six (1.10.0)
system-service (0.3)
thin-client-config-agent (0.8)
ubuntu-drivers-common (0.0.0)
ufw (0.35)
urllib3 (1.13.1)
virtkey (0.63.0)
xkit (0.0.0)

**Comment by eploft** [comment]
Update: it works with construct version 2.8.2 (just tried one older version > 2.8)

**Comment by arekbulski** [comment]
The PR was merged way back. Should this ticket not be closed?
