### ISSUE TITLE
OSError: open failed

### ISSUE THREAD

**Issue by dagord** [glucometers-tech/glucometerutils#50]
I have a problem connecting with my Freestyle libre.
If I enter  **glucometer --driver fslibre help** I get this message, so the device is correctly found (I guess)
```
Driver for FreeStyle Libre devices.

Supported features:
    - get readings (sensor, flash and blood glucose), including comments;
    - get and set date and time;
    - get serial number and software version.

Expected device path: /dev/hidraw9 or similar HID device. Optional when using
HIDAPI.
```
But if I type **glucometer --driver fslibre info** (or **dump**) I get:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/glucometerutils/support/hiddevice.py", line 74, in __init__
    self.USB_VENDOR_ID, self.USB_PRODUCT_ID)
  File "hid.pyx", line 66, in hid.device.open
OSError: open failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/glucometer", line 11, in <module>
    load_entry_point('glucometerutils==1', 'console_scripts', 'glucometer')()
  File "/usr/local/lib/python3.5/dist-packages/glucometerutils/glucometer.py", line 83, in main
    device = driver.Device(args.device)
  File "/usr/local/lib/python3.5/dist-packages/glucometerutils/support/hiddevice.py", line 80, in __init__
    message='Unable to connect to meter: %s.' % e)
  File "/usr/local/lib/python3.5/dist-packages/glucometerutils/exceptions.py", line 21, in __init__
    super(ConnectionFailed, self).__init__(message=message)
TypeError: ConnectionFailed does not take keyword arguments

```
So, it seems the connection can't be openend.
I'm working with a docker Debian 9 container (under Ubuntu 16.04); I installed all the required dependencies

**Comment by dagord** [comment]
You are right. I created a new user and added it to the "sudoers" group, then I can run the script using sudo.
But now I get another error:
```
  File "./glucometer.py", line 7, in <module>
    glucometer.main()
  File "/home/test/scripts/glucometerutils/glucometerutils/glucometer.py", line 85, in main
    device.connect()
  File "/home/test/scripts/glucometerutils/glucometerutils/support/freestyle.py", line 96, in connect
    self._read_response()
  File "/home/test/scripts/glucometerutils/glucometerutils/support/freestyle.py", line 119, in _read_response
    usb_packet = self._read()
  File "/home/test/scripts/glucometerutils/glucometerutils/support/hiddevice.py", line 105, in _read
    size, timeout_ms=self.TIMEOUT_MS))
  File "hid.pyx", line 102, in hid.device.read
TypeError: an integer is required

```

**Comment by Flameeyes** [comment]
Okay that particular problem should be fixed now. It looks like hidapi changed its interface ever so slightly and I have not been testing this with hidapi installed.

**Comment by dagord** [comment]
Ok, fine. I'll try again as soon as possibile!

**Comment by dagord** [comment]
I confirm it works now!
